workflows:
  android-release:
    name: Native Android release
    max_build_duration: 60
    instance_type: windows_x2
    environment:
      groups:
        - keystore_credentials
      vars:
        CM_KEYSTORE_PATH: /tmp/keystore.keystore
      node: latest
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Log folders
        script: pwd ; ls $CM_BUILD_DIR
      - name: Flutter doctor
        script: flutter doctor
      - name: Get Flutter packages
        script: |
          cd mobile_player_sdk
          flutter packages pub get
      - name: Flutter analyze
        script: |
          cd mobile_player_sdk
          flutter analyze
      - name: Flutter tests
        script: |
          cd mobile_player_sdk
          flutter test
        ignore_failure: true
      - name: Precompile the Flutter module with release version
        script: |
          cd mobile_player_sdk
          flutter build aar --release --no-debug --no-profile --scan
      - name: Set up local properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/mobile_player_android/local.properties"
      - name: Set up key.properties file for code signing
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
          cat >> "$CM_BUILD_DIR/mobile_player_android/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=$CM_KEYSTORE_PATH
          EOF    
      - name: Build release apk 
        script: |
          cd mobile_player_android
          ./gradlew assembleRelease
    artifacts:
      - mobile_player_sdk/build/host/outputs/repo/com/vidvi/mobileplayersdk/flutter_release/*/*.aar
      - mobile_player_android/app/build/outputs/apk/*/*.apk
    publishing:
      email:
        recipients:
          - daniel.zaczek@appwise.pl
          
  android-debug:
    name: Native Android debug
    max_build_duration: 60
    instance_type: windows_x2
    scripts:
      - name: Set up local properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/mobile_player_android/local.properties"
      - name: Precompile the Flutter module with debug version
        script: |
          cd mobile_player_sdk
          flutter build aar --debug --no-release --no-profile  
      - name: Build debug apk
        script: |
          cd mobile_player_android
          ./gradlew assembleDebug
    artifacts:
      - mobile_player_sdk/build/host/outputs/repo/com/vidvi/mobileplayersdk/flutter_debug/*/*.aar
      - mobile_player_android/app/build/outputs/apk/*/*.apk
    publishing:
      email:
        recipients:
          - daniel.zaczek@appwise.pl
